### ISSUE TITLE
"bot" object on attribute 'send_typing' how to fix 

### ISSUE THREAD

**Issue by JabzEz** [DevDungeon/Cathy#10]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\py\lib\site-packages\discord\cli
line 255, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\py\lib\site-packages\cathy\cathy
e 55, in on_ready
    yield from self.discord_client.change_presence(game=discord.Game(na
ing with Humans'))
TypeError: change_presence() got an unexpected keyword argument 'game'

**Comment by JabzEz** [comment]
![image](https://user-images.githubusercontent.com/47947224/56462622-a9962100-63f0-11e9-9777-73f0f44a0609.png)

**Comment by JabzEz** [comment]
pip install cathy 
using python <3.7 and discord.py==0.16.12
windows server 2012 r2
Help

**Comment by NanoDano** [comment]
Unable to recreate with cathy 1.1.5 in Windows. Try creating a clean virtual environment.

**Comment by NanoDano** [comment]
Also, the AIML parse errors are unrelated, and expected.
