### ISSUE TITLE
Issue with cathy!

### ISSUE THREAD

**Issue by snaildos** [DevDungeon/Cathy#11]
Hey! This is my first time using a AIML based ai chatbot on discord!
Running chatty cathy results with a error!
I installed through:
pip install cathy

And get this error:
Loading C:\Python37\lib\site-packages\cathy\std-startup.xml...done (0.01 seconds)
PARSE ERROR: Unexpected <category> tag (line 40, column 0)
PARSE ERROR: Unexpected </category> tag (line 43, column 0)
Loading aiml\alice\ai.aiml...done (0.02 seconds)
Loading aiml\alice\alice.aiml...done (0.02 seconds)
Loading aiml\alice\astrology.aiml...done (0.00 seconds)
PARSE ERROR: Unexpected text inside <random> element (line 3383, column 0)
Loading aiml\alice\atomic.aiml...done (0.25 seconds)
PARSE ERROR: Unexpected <category> tag (line 100, column 1)
PARSE ERROR: Unexpected </learn> tag (line 108, column 0)
PARSE ERROR: Unexpected </li> tag (line 110, column 0)
PARSE ERROR: Unexpected </condition> tag (line 128, column 0)
PARSE ERROR: Unexpected </template> tag (line 129, column 0)
PARSE ERROR: Unexpected </category> tag (line 130, column 0)
PARSE ERROR: Unexpected <category> tag (line 158, column 1)
PARSE ERROR: Unexpected </learn> tag (line 166, column 0)
PARSE ERROR: Unexpected </li> tag (line 168, column 0)
PARSE ERROR: Unexpected </condition> tag (line 173, column 0)
PARSE ERROR: Unexpected </template> tag (line 174, column 0)
PARSE ERROR: Unexpected </category> tag (line 175, column 0)
Loading aiml\alice\badanswer.aiml...done (0.01 seconds)
Loading aiml\alice\biography.aiml...done (0.05 seconds)
Loading aiml\alice\bot.aiml...done (0.23 seconds)
Loading aiml\alice\bot_profile.aiml...done (0.01 seconds)
PARSE ERROR: <random> elements can only contain <li> subelements (line 443, column 495)
PARSE ERROR: <random> elements can only contain <li> subelements (line 1733, column 19)
Loading aiml\alice\client.aiml...done (0.16 seconds)
Loading aiml\alice\client_profile.aiml...done (0.03 seconds)
Loading aiml\alice\computers.aiml...done (0.01 seconds)
Loading aiml\alice\continuation.aiml...done (0.00 seconds)
Loading aiml\alice\date.aiml...done (0.00 seconds)
PARSE ERROR: Unexpected text inside <random> element (line 4311, column 262)
PARSE ERROR: Unexpected text inside <random> element (line 4848, column 172)
PARSE ERROR: Unexpected text inside <random> element (line 8844, column 351)
Loading aiml\alice\default.aiml...done (0.47 seconds)
Loading aiml\alice\drugs.aiml...done (0.01 seconds)
Loading aiml\alice\emotion.aiml...done (0.01 seconds)
Loading aiml\alice\food.aiml...done (0.00 seconds)
Loading aiml\alice\geography.aiml...done (0.10 seconds)
Loading aiml\alice\gossip.aiml...done (0.00 seconds)
Loading aiml\alice\history.aiml...done (0.00 seconds)
Loading aiml\alice\humor.aiml...done (0.00 seconds)
Loading aiml\alice\imponderables.aiml...done (0.00 seconds)
Loading aiml\alice\inquiry.aiml...done (0.01 seconds)
Loading aiml\alice\interjection.aiml...done (0.00 seconds)
Loading aiml\alice\iu.aiml...done (0.00 seconds)
Loading aiml\alice\knowledge.aiml...done (0.15 seconds)
Loading aiml\alice\literature.aiml...done (0.00 seconds)
Loading aiml\alice\loebner10.aiml...done (0.00 seconds)
Loading aiml\alice\money.aiml...done (0.01 seconds)
Loading aiml\alice\movies.aiml...done (0.01 seconds)
Loading aiml\alice\mp0.aiml...done (0.46 seconds)
Loading aiml\alice\mp1.aiml...done (0.47 seconds)
Loading aiml\alice\mp2.aiml...done (0.53 seconds)
Loading aiml\alice\mp3.aiml...done (0.52 seconds)
Loading aiml\alice\mp4.aiml...done (0.48 seconds)
Loading aiml\alice\mp5.aiml...done (0.60 seconds)
Loading aiml\alice\mp6.aiml...done (0.26 seconds)
Loading aiml\alice\music.aiml...done (0.00 seconds)
Loading aiml\alice\numbers.aiml...done (0.04 seconds)
Loading aiml\alice\personality.aiml...done (0.02 seconds)
Loading aiml\alice\phone.aiml...done (0.00 seconds)
Loading aiml\alice\pickup.aiml...done (0.01 seconds)
Loading aiml\alice\politics.aiml...done (0.01 seconds)
Loading aiml\alice\primeminister.aiml...done (0.00 seconds)
PARSE ERROR: Unexpected <category> tag (line 18, column 0)
PARSE ERROR: Unexpected </learn> tag (line 22, column 0)
PARSE ERROR: Unexpected </template> tag (line 35, column 0)
PARSE ERROR: Unexpected </category> tag (line 36, column 0)
Loading aiml\alice\primitive-math.aiml...done (0.01 seconds)
Loading aiml\alice\psychology.aiml...done (0.08 seconds)
Loading aiml\alice\pyschology.aiml...done (0.06 seconds)
Loading aiml\alice\reduction.names.aiml...done (0.39 seconds)
Loading aiml\alice\reduction0.safe.aiml...done (0.59 seconds)
Loading aiml\alice\reduction1.safe.aiml...done (0.76 seconds)
Loading aiml\alice\reduction2.safe.aiml...done (0.36 seconds)
Loading aiml\alice\reduction3.safe.aiml...done (0.50 seconds)
Loading aiml\alice\reduction4.safe.aiml...done (1.03 seconds)
Loading aiml\alice\reductions-update.aiml...done (0.02 seconds)
Loading aiml\alice\religion.aiml...done (0.04 seconds)
Loading aiml\alice\salutations.aiml...done (0.02 seconds)
Loading aiml\alice\science.aiml...done (0.00 seconds)
Loading aiml\alice\sex.aiml...done (0.05 seconds)
Loading aiml\alice\sports.aiml...done (0.00 seconds)
Loading aiml\alice\stack.aiml...done (0.00 seconds)
Loading aiml\alice\stories.aiml...done (0.04 seconds)
Loading aiml\alice\that.aiml...done (0.24 seconds)
PARSE ERROR: <random> elements can only contain <li> subelements (line 3374, column 125)
Loading aiml\alice\update1.aiml...done (0.91 seconds)
PARSE ERROR: Unexpected </category> tag (line 104, column 0)
PARSE ERROR: Unexpected </category> tag (line 144, column 0)
Loading aiml\alice\update_mccormick.aiml...done (0.02 seconds)
Loading aiml\alice\wallace.aiml...done (0.14 seconds)
Loading aiml\alice\xfind.aiml...done (0.01 seconds)
Loading aiml\custom\basic_chat.aiml...done (0.00 seconds)
Bot Online!
Name: 1
ID: 1
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "C:\Python37\lib\site-packages\cathy\cathy.py", line 55, in on_ready
    yield from self.discord_client.change_presence(game=discord.Game(name='Chatting with Humans'))
TypeError: change_presence() got an unexpected keyword argument 'game'

Is there a solution?
BTW: I changed name and id

**Comment by snaildos** [comment]
Also, I wanted to know, will cathy save things?
Like:
My cat is called elen

What is my cat called?

And it would save for individual users?

**Comment by snaildos** [comment]
Ok so I removed that line, Then, I talked in the channel, NOTHING happend! And, no errors were logged.

**Comment by NanoDano** [comment]
You are using the wrong versions of both Python and discord.py. Refer to setup.py
