### ISSUE TITLE
Just checking the bits

### ISSUE THREAD

**Issue by IBP-0** [DevDungeon/Cathy#19]
Things like `bot name=order/`
in 
https://github.com/DevDungeon/Cathy/blob/master/cathy/aiml/alice/drugs.aiml

Do not seem to be working. 

In reference to this; 

`category` `pattern`I TOLD YOU YOU *`/pattern`
`template` `srai` you `star /` `/srai` `/template`

I also got this; 

![image](https://user-images.githubusercontent.com/61919539/76689619-15d3d180-660e-11ea-9f88-74a30c4c24ba.png)

It is a mystery. 

Cheers.

**Comment by NanoDano** [comment]
try adding one more word for the pattern to match, `i told you you something`

**Comment by IBP-0** [comment]
That's good information.
