### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by nikagl** [DevDungeon/Cathy#20]
Hi all,

I hadn't used the bot for a while, was still using the old version where the log and db needed to be specified in the command line.

DIscord disabled the token somewhere, because of too many requests and I turned it off for later investigation.

Today I upgraded the bot, it does come online now, but it does not respond.

Even when I load your bot, give it permission to the channel, it comes online, but does not respond to questions anymore.

What's going on?

Regards,

Nika.

**Comment by NanoDano** [comment]
Make sure you have the latest version of discord.py

**Comment by NanoDano** [comment]
The docs have been updated with notes about the new way to run it; https://cathy-docs.readthedocs.io/en/latest/

**Comment by nikagl** [comment]
Superb, "py -3 -m pip install -U discord.py" fixed it. Not sure why inviting your bot didn't work, but guess the two bots might have conflicted...?
